# Generated by Django 5.2.3 on 2025-07-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_record_delete_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="listened_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="opinion",
            field=models.CharField(
                choices=[("bad", "Bad"), ("good", "Good"), ("great", "Great")],
                null=True,
            ),
        ),
    ]
