# Generated by Django 5.2.3 on 2025-07-19 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_record_listened_at_alter_record_opinion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="opinion",
            field=models.CharField(
                blank=True,
                choices=[("bad", "Bad"), ("good", "Good"), ("great", "Great")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
